### ISSUE TITLE
TextureFormat issue on 2018.2.4

### ISSUE THREAD

**Issue by rroc** [keijiro/ShaderGraphExamples#2]
The new Unity version gives errors like this:

	ArgumentException: Failed SupportsTextureFormat; format is not a valid TextureFormat
	UnityEngine.SystemInfo.SupportsTextureFormat (TextureFormat format) (at C:/buildslave/unity/build/Runtime/Export/SystemInfo.bindings.cs:384)
	UnityEngine.Rendering.PostProcessing.TextureFormatUtilities..cctor () (at Unity/cache/packages/packages.unity.com/com.unity.postprocessing@2.0.5-preview/PostProcessing/Runtime/Utils/TextureFormatUtilities.cs:98)
	Rethrow as TypeInitializationException: An exception was thrown by the type initializer for UnityEngine.Rendering.PostProcessing.TextureFormatUtilities
	UnityEngine.Rendering.PostProcessing.AmbientOcclusion.IsEnabledAndSupported (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Unity/cache/packages/packages.unity.com/com.unity.postprocessing@2.0.5-preview/PostProcessing/Runtime/Effects/AmbientOcclusion.cs:100)
	UnityEngine.Rendering.PostProcessing.PostProcessLayer.SetLegacyCameraFlags (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Unity/cache/packages/packages.unity.com/com.unity.postprocessing@2.0.5-preview/PostProcessing/Runtime/PostProcessLayer.cs:517)
	UnityEngine.Rendering.PostProcessing.PostProcessLayer.SetupContext (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Unity/cache/packages/packages.unity.com/com.unity.postprocessing@2.0.5-preview/PostProcessing/Runtime/PostProcessLayer.cs:572)
	UnityEngine.Rendering.PostProcessing.PostProcessLayer.Render (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Unity/cache/packages/packages.unity.com/com.unity.postprocessing@2.0.5-preview/PostProcessing/Runtime/PostProcessLayer.cs:629)
	UnityEngine.Experimental.Rendering.LightweightPipeline.LightweightPipeline.RenderPostProcess (UnityEngine.Rendering.CommandBuffer cmd, RenderTargetIdentifier source, RenderTargetIdentifier dest, Boolean opaqueOnly) (at Unity/cache/packages/packages.unity.com/com.unity.render-pipelines.lightweight@1.1.5-preview/LWRP/LightweightPipeline.cs:1499)
	UnityEngine.Experimental.Rendering.LightweightPipeline.LightweightPipeline.AfterTransparent (UnityEngine.Experimental.Rendering.ScriptableRenderContext& context, FrameRenderingConfiguration config) (at Unity/cache/packages/packages.unity.com/com.unity.render-pipelines.lightweight@1.1.5-preview/LWRP/LightweightPipeline.cs:587)
	UnityEngine.Experimental.Rendering.LightweightPipeline.LightweightPipeline.ForwardPass (System.Collections.Generic.List`1 visibleLights, FrameRenderingConfiguration frameRenderingConfiguration, UnityEngine.Experimental.Rendering.ScriptableRenderContext& context, UnityEngine.Experimental.Rendering.LightweightPipeline.LightData& lightData, Boolean stereoEnabled) (at Unity/cache/packages/packages.unity.com/com.unity.render-pipelines.lightweight@1.1.5-preview/LWRP/LightweightPipeline.cs:495)
	UnityEngine.Experimental.Rendering.LightweightPipeline.LightweightPipeline.Render (ScriptableRenderContext context, UnityEngine.Camera[] cameras) (at Unity/cache/packages/packages.unity.com/com.unity.render-pipelines.lightweight@1.1.5-preview/LWRP/LightweightPipeline.cs:373)
	UnityEngine.Experimental.Rendering.RenderPipelineManager.DoRenderLoop_Internal (IRenderPipelineAsset pipe, UnityEngine.Camera[] cameras, IntPtr loopPtr) (at C:/buildslave/unity/build/Runtime/Export/RenderPipeline/RenderPipelineManager.cs:32)
	UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by keijiro** [comment]
Thanks for reporting the issue. It's fixed in d3918822d81825389df741bc86c86cdbb979fb7e
